apiVersion: v1
kind: Service
metadata:
  name: '{{ include "portfolio-app.fullname" . }}'
  labels:
    app: '{{ include "portfolio-app.name" . }}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: '{{ include "portfolio-app.name" . }}'
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
